spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: test
    region:
      static: test
    credentials:
      access-key: test
      secret-key: test

file:
  dir: "${pwd}/../"
  post: "post-image/"
  user: "user-image/"

tag:
  tag:
    pattern: "#[ㄱ-ㅎ|가-힣|a-z|A-Z|\\d|_]+"
  user:
    pattern: "@[a-z|A-Z|\\d|_]+"

jwt:
  token:
    header: Authorization
    issuer: sidepr
    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expiry-seconds: 0